backend:
  name: git-gateway
  branch: static # Branch to update (optional; defaults to master)
display_url: https://static.taxtherich.com

publish_mode: editorial_workflow
media_folder: "source/assets/build/images"
public_folder: "assets/build/images/uploads"
logo_url: https://tinypixel.io/app/uploads/2019/03/tiny-pixel-horizontal-small-black.png
show_preview_links: true

collections:
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    description: >
      All my blog posts
    folder: "source/_posts"
    slug: "{{slug}}"
    extension: "md"
    format: "yaml-frontmatter"
    create: true
    identifier_field: "heading"
    fields:
      - { label: "Heading", name: "heading", widget: "string", required: true, default: "" }
      - { label: "Subheading", name: "subheading", widget: "string", required: true, default: "" }
      - { label: "Disclaimer", name: "disclaimer", widget: "string", required: true, default: "" }
      - { label: "Section One Heading", name: "section_one_heading", widget: "string", required: true, default: "" }
      - { label: "Section One Content", name: "section_one_content", widget: "markdown", required: true, default: "" }
      - { label: "Section One List Item One", name: "section_one_li_one", widget: "string", required: true, default: "" }
      - { label: "Section One List Item Two", name: "section_one_li_two", widget: "string", required: true, default: "" }
      - { label: "Section One List Item Three", name: "section_one_li_three", widget: "string", required: true, default: "" }
      - { label: "Section Two Heading", name: "section_two_heading", widget: "string", required: true, default: "" }
      - { label: "Section Two Column One Heading", name: "section_two_column_one_heading", widget: "string", required: true, default: "" }
      - { label: "Section Two Column One Content", name: "section_two_column_one_content", widget: "markdown", required: true, default: "" }
      - { label: "Section Two Column Two Heading", name: "section_two_column_two_heading", widget: "string", required: true, default: "" }
      - { label: "Section Two Column Two Content", name: "section_two_column_two_content", widget: "markdown", required: true, default: "" }
      - { label: "Section Two Column Three Heading", name: "section_two_column_three_heading", widget: "string", required: true, default: "" }
      - { label: "Section Two Column Three Content", name: "section_two_column_three_heading", widget: "markdown", required: true, default: "" }

